# Generated by Django 5.1.6 on 2025-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_indicator_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='threshold',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='description',
        ),
        migrations.AddField(
            model_name='alert',
            name='indicator1_params',
            field=models.CharField(default='{}', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='indicator2_params',
            field=models.CharField(default='{}', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='condition',
            field=models.CharField(choices=[('above', 'Crosses Above'), ('below', 'Crosses Below'), ('equals', 'Equals')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timeframe',
            field=models.CharField(choices=[('1min', '1 Minute'), ('5min', '5 Minutes'), ('15min', '15 Minutes'), ('1day', 'Daily')], max_length=10),
        ),
    ]
