# Generated by Django 5.1.6 on 2025-04-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_alert_threshold_remove_indicator_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='timeframe',
            field=models.CharField(choices=[('1min', '1 Minute'), ('5min', '5 Minutes'), ('15min', '15 Minutes'), ('4h', '4 Hours'), ('1day', '1 Day'), ('1week', '1 Week')], max_length=10),
        ),
    ]
