# Generated by Django 5.1.6 on 2025-04-14 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alert_alert_type_alter_alert_stock_stockgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('email_address', models.EmailField(blank=True, help_text='Email address for notifications', max_length=254, null=True)),
                ('sms_enabled', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for SMS notifications', max_length=20, null=True)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', help_text='How frequently notifications should be sent', max_length=20)),
                ('notify_on_rsi', models.BooleanField(default=True, help_text='Receive notifications for RSI alerts')),
                ('notify_on_macd', models.BooleanField(default=True, help_text='Receive notifications for MACD alerts')),
                ('notify_on_moving_avg', models.BooleanField(default=True, help_text='Receive notifications for Moving Average alerts')),
                ('notify_on_bollinger', models.BooleanField(default=True, help_text='Receive notifications for Bollinger Band alerts')),
                ('alert_types', models.CharField(default='all', help_text="Comma-separated list of alert types or 'all' for all alerts", max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
