# Generated by Django 5.1.6 on 2025-05-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_usernotificationpreferences_alert_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('triggered', 'Triggered'), ('deleted', 'Deleted'), ('modified', 'Modified')], max_length=20)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.alert')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
